//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanatana.EntityFramework.BatchSpecs.Resources.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sanatana.EntityFramework.BatchSpecs.Resources.Scripts.ScriptRes", typeof(ScriptRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[AuthTokens_Insert]
        ///	@accountUid UNIQUEIDENTIFIER,
        ///	@token NVARCHAR(100)
        ///AS
        ///
        ///DELETE AuthTokens
        ///WHERE Token = @token
        ///
        ///MERGE AuthTokens AS target
        ///USING (SELECT @accountUid, @token) AS source (AccountUid, Token)
        ///ON (target.AccountUID = source.AccountUid)
        ///WHEN MATCHED THEN 
        ///    UPDATE SET Token = source.Token,
        ///	CreateDateUtc = GETUTCDATE()
        ///WHEN NOT MATCHED THEN	
        ///	INSERT (AccountUid, Token, CreateDateUtc)
        ///	VALUES (source.AccountUid, source.Token, GETUTCDATE());.
        /// </summary>
        internal static string AuthTokens_Insert {
            get {
                return ResourceManager.GetString("AuthTokens_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[SiteLogins] (
        ///    [UID]                              UNIQUEIDENTIFIER NOT NULL,
        ///    [Email]                            NVARCHAR (256)   NOT NULL,
        ///    [Password]                         NVARCHAR (128)   NOT NULL,
        ///    [DisplayName]                      NVARCHAR (64)    NOT NULL,
        ///    [IsEmailVerified]                  BIT              CONSTRAINT [DF_SiteLogins_IsEmailVerified] DEFAULT ((0)) NOT NULL,
        ///    [CreatedTime]                      DATETIME         CONSTRAINT [DF_SiteLogins_Cre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SiteLogins {
            get {
                return ResourceManager.GetString("SiteLogins", resourceCulture);
            }
        }
    }
}
